FastScore/TestProject/Controllers/MatchesController.cs
using Data;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Mapping;

namespace TestProject.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly FastScoreContext context;

        public MatchesController(IUnitOfWork unitOfWork, FastScoreContext context)
        {
            this.unitOfWork = unitOfWork;
            this.context = context;
        }


        public async Task<IActionResult> GetAllWithOdds(int sportId, DateTime date)
        {
            var leaguesMatches = await this.unitOfWork.MatchesService.GetAllWithOdds(sportId, date);

            if (!leaguesMatches.Any())
            {
                var sport = await this.unitOfWork.SportsService.GetByIdAsync(sportId);

                return PartialView("_NoMatchFound", model: sport.PhotoUrl);
            }

            var leaguesMatchesVM = ViewModelMapper.Map(leaguesMatches);

            return PartialView("_GetMatches", leaguesMatchesVM);
        }

        public async Task<IActionResult> GetAll(int sportId, DateTime date)
        {
            var leaguesMatches = await this.unitOfWork.MatchesService.GetAll(sportId, date);

            if (!leaguesMatches.Any())
            {
                return PartialView("_NoMatchFound", model: sportId);
            }

            var leaguesMatchesVM = ViewModelMapper.Map(leaguesMatches);

            return PartialView("_GetMatches", leaguesMatchesVM);
        }

        public async Task<IActionResult> GetByDate(int sportId, DateTime date)
        {
            var matchesByDate = await unitOfWork.MatchesService.GetByDate(sportId, date);

            if (!matchesByDate.Any())
            {
                var sport = await this.unitOfWork.SportsService.GetByIdAsync(sportId);

                return PartialView("_NoMatchFound", sport.PhotoUrl);
            }

            var matchesByDateVM = ViewModelMapper.Map(matchesByDate);

            return PartialView("_GetMatches", matchesByDateVM);
        }

        public async Task<IActionResult> GetByMatchStatusId(int sportId, int matchStatusId, DateTime date)
        {
            var matchesByMatchStatusId = await unitOfWork.MatchesService.GetByMatchStatusId(sportId, matchStatusId, date);

            if (!matchesByMatchStatusId.Any())
            {
                var sport = await this.unitOfWork.SportsService.GetByIdAsync(sportId);

                return PartialView("_NoMatchFound", sport.PhotoUrl);
            }

            var matchesByMatchStatus = ViewModelMapper.Map(matchesByMatchStatusId);

            return PartialView("_GetMatches", matchesByMatchStatus);
        }
    }
}

FastScore/TestProject/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager;
@inject UserManager<User> userManager;
@inject IUnitOfWork unitOfWork;
@inject FastScoreContext context;

@{
    User user = null;

    @if (signInManager.IsSignedIn(User))
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        user = await context.Users
            .Include(u => u.FavoriteMatches)
            .Include(u => u.Leagues)
            .ThenInclude(l => l.Country)
            .FirstOrDefaultAsync(u => u.Id == userId);
    }

    var sports = await unitOfWork.SportsService.GetAll();
    var sportsWithTodaysMatchesCount = new Dictionary<Sport, int>();

    foreach (var sport in sports)
    {
        var sportTodaysMatchesCount = unitOfWork.MatchesService.GetTodayMatchesCount(sport.Id);
        sportsWithTodaysMatchesCount.Add(sport, sportTodaysMatchesCount);
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @if (IsSectionDefined("Styles"))
    {
        @RenderSection("Styles", required: false);
    }
</head>
<body>
    <header>
        <div class="containerr">
            <div class="free-space-nav"></div>
            <div class="nav">
                <div class="special-container">
                    <div class="image">
                        <img id="logo" src="~/imges/logo.png" />
                    </div>
                    <div class="text">
                        <p><span class="logoText">FastScore</span><span class="logoText" style="font-size: 12px;">We deliver scores faster</span></p>
                    </div>
                </div>
                <div class="special-container" id="loginForm">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <div class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout @user.UserName</a>
                        </div>
                    }
                    else
                    {
                        <div class="nav-item">
                            <a class="nav-link" id="login" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link" id="register" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </div>
                    }
                </div>
            </div>
            <div class="free-space-nav"></div>
        </div>
        <div class="containerr">
            <div class="free-space-nav"></div>
            <div class="nav">
                <a asp-action="GetFavoriteMatches" asp-controller="Account" class="sports">
                    <div class="special-container">
                        <div class="image">
                            <img class="sportsImg" src="~/imges/full_star.png" alt="favoriteMatchesStarImage" />
                        </div>
                        <div class="text">
                            FAVORITES
                        </div>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <div id="favoritesDot" class="dot">@user.FavoriteMatches.Count()</div>
                        }
                        else
                        {
                            <div class="dot">0</div>
                        }
                    </div>
                </a>

                @foreach (var kvp in sportsWithTodaysMatchesCount)
                {
                    @if (kvp.Key.Id == SportIdsConsts.FOOTBALL_ID)
                    {
                        <a id="currSport" asp-action="GetByDate" asp-controller="Matches" asp-route-sportId="@kvp.Key.Id" asp-route-date="@DateTime.Today.ToString()" class="sports">
                            <div class="special-container">
                                <div class="image">
                                    <img class="sportsImg" src="@kvp.Key.PhotoUrl" />
                                </div>
                                <div class="text">
                                    @kvp.Key.Name.ToUpper()
                                </div>
                                <div class="dot">@kvp.Value</div>
                            </div>
                        </a>
                    }
                    else
                    {
                        <a asp-action="GetTodayMatches" asp-controller="Matches" asp-route-sportId="@kvp.Key.Id" class="sports">
                            <div class="special-container">
                                <div class="image">
                                    <img class="sportsImg" src="@kvp.Key.PhotoUrl" />
                                </div>
                                <div class="text">
                                    @kvp.Key.Name.ToUpper()
                                </div>
                                <div class="dot"><span>@kvp.Value</span></div>
                            </div>
                        </a>
                    }
                }

                <a id="more-a" class="sports">
                    <div class="special-container">
                        <div class="image">
                            <img id="more-sports-image" class="sportsImg" src="~/imges/triangle_down.png" alt="favoriteMatchesStarImage" />
                        </div>
                        <div class="text">
                            MORE
                        </div>
                    </div>
                </a>
            </div>
            <div class="free-space-nav"></div>
        </div>
    </header>
    <div class="body-container" style="display:table">
        <div style="display:table-cell" class="free-space"></div>
        <div id="main-content" style="display: table-cell">
            <div style="display:table-cell" id="left-div">
                <div class="column-special-container">
                    <div id="flex-row-my-leagues">
                        <div id="my-leagues-div" class="special-container">
                            <div><img id="my-leagues-star-img" src="~/imges/full_star.png" /></div>
                            <div id="my-leagues-inner-div"><span id="my-leagues">My Leagues</span></div>
                        </div>
                    </div>
                    @if (user != null)
                    {
                        <div id="user-favorite-leagues">
                            @foreach (var league in user.Leagues)
                            {
                                <div class="flex-row-league" leagueId="@league.Id" leagueCountryName="@league.Country.Name">
                                    <div class="special-container">
                                        <div>
                                            <img class="country-flag" src="@league.Country.FlagPhotoUrl">
                                        </div>
                                        <div class="my-leagues-league-name">
                                            <span>@league.Name</span>
                                        </div>
                                        <div class="cross" leagueId="@league.Id">
                                            <img class="cross-img" leagueId="@league.Id" src="/imges/cross.png" />
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                    <div class="flex-row-bet365-img">
                        <img src="" />
                    </div>
                </div>
            </div>
            <div style="display:table-cell" id="middle-div">
                <main id="main" role="main" class="pb-3">
                    <div id="middle-menu" class="special-container">
                        <div class="special-container" id="management">
                            <div class="special-container" id="match-menu">
                                <div id="all-matches-div">
                                    <div id="all-games-container" sportId="@SportIdsConsts.FOOTBALL_ID">
                                        <div class="menu">
                                            <span class="menu-item">All Games</span>
                                        </div>
                                    </div>
                                    <div class="get-by-matchstatus-item" sportId="@SportIdsConsts.FOOTBALL_ID" matchStatusId="@MatchStatusIdsConsts.IN_PLAY">
                                        <div id="live-matches" class="menu">
                                            <span class="menu-item">LIVE Games</span>
                                        </div>
                                    </div>
                                    <div id="matches-odds-container" sportId="@SportIdsConsts.FOOTBALL_ID">
                                        <div class="menu">
                                            <span class="menu-item">Odds</span>
                                        </div>
                                    </div>
                                    <div class="get-by-matchstatus-item" sportId="@SportIdsConsts.FOOTBALL_ID" matchStatusId="@MatchStatusIdsConsts.FINISHED">
                                        <div id="finished-matches" class="menu">
                                            <span class="menu-item">Finished</span>
                                        </div>
                                    </div>
                                    <div class="get-by-matchstatus-item" sportId="@SportIdsConsts.FOOTBALL_ID" matchStatusId="@MatchStatusIdsConsts.SCHEDULED">
                                        <div id="scheduled-matches" class="menu">
                                            <span class="menu-item">Scheduled</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="special-container" id="manageDates">
                            <div style="position:relative">
                                <div class="special-container">
                                    <div id="left-arrow" class="arrow">
                                        <img class="arrow-img" src="/imges/left_arrow.png" />
                                    </div>
                                    <div id="calendar-div">
                                        <div>
                                            <img id="calendar-img" src="~/imges/callendar.png" /><span id="calendar-date">@DateTime.Today.ToString("dd/MM ddd")</span>
                                        </div>
                                        <div class="custom-dropdown" id="date-dropdown">
                                            @for (int previousDays = -7; previousDays <= -1; previousDays++)
                                            {
                                                var date = DateTime.Today.AddDays(previousDays);
                                                <div id="not-today-date" class="custom-dropdown-item">
                                                    @date.ToString("dd/MM ddd")
                                                </div>
                                            }

                                            <div id="custom-dropdown-today-a" class="custom-dropdown-item">
                                                <a>Today</a>
                                            </div>

                                            @for (int incomingDays = 1; incomingDays < 7; incomingDays++)
                                            {
                                                var date = DateTime.Today.AddDays(incomingDays);
                                                <div id="not-today-date" class="custom-dropdown-item">
                                                    @date.ToString("dd/MM ddd")
                                                </div>
                                            }
                                        </div>
                                    </div>
                                    <div id="right-arrow" class="arrow">
                                        <a><img class="arrow-img" src="~/imges/right_arrow.png" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="custom-padding"></div>
                    <div id="partial-body-content">
                        @RenderBody()
                    </div>
                </main>
            </div>
            <div style="display:table-cell" id="right-div">
                @*<img style="display:block" id="bet365-promo" src="~/imges/bet365-promo.jpg" />*@
            </div>
        </div>
        <div style="display:table-cell" class="free-space"></div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FastScore/TestProject/Views/Shared/_Layout_Tennis.cshtml
@inject SignInManager<User> signInManager;
@inject UserManager<User> userManager;
@inject IUnitOfWork unitOfWork;
@inject FastScoreContext context;

@{
    User user = null;

    @if (User.Identity.IsAuthenticated)
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        user = await context.Users.Include(u => u.FavoriteMatches).FirstOrDefaultAsync(u => u.Id == userId);
        var userFavorites = user.FavoriteMatches;
    }

    var sports = await unitOfWork.SportsService.GetAll();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site_tennis.css" />
    <link href="~/css/secondNavBar.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container">
                <a class="navbar-brand" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="special-container">
                        <div class="image">
                            <img id="logo" src="~/imges/Uvf86ufG_400x400.png" />
                        </div>
                        <div class="text">
                            <p><span class="logoText">FastScore</span><span class="logoText" style="font-size: 12px;">We deliver scores faster</span></p>
                        </div>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar -collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout @user.UserName</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" id="login" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="register" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <nav id="bottomNav" class="navbar navbar-expand-sm navbar-light">
            <div class="container">
                <div class="navbar -collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="background-color:darkgreen">
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        @foreach (var sport in sports)
                        {
                            @if (sport.IsFavoriteSport)
                            {
                                <li class="nav-item">
                                    <a asp-action="GetTodayMatches" asp-controller="Matches" asp-route-sportId="@sport.Id" class="sports">
                                        <div class="special-container">
                                            <div class="image">
                                                <img class="sportsImg" src="@sport.PhotoUrl" />
                                            </div>
                                            <div class="text">
                                                @sport.Name
                                            </div>
                                            <div class="dot">1</div>
                                        </div>
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FastScore/TestProject/Views/Shared/_NoMatchFound.cshtml
@model string


<div id="container">
    <img style="margin-left:auto; margin-right:auto; width:20px; height:20px; display:block" src="@Model" />
    <p style="margin-left:auto; margin-right:auto; text-align:center">No match found.</p>
</div>